[opener]
edit = [
    { run = 'nvim "$@"', desc = "nvim", block = true, for = "unix" },
    # Keep the default as a fallback option if needed
    # { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
]   
